//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VM.DataAccessLayer.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileRepositoryTable
    {
        public FileRepositoryTable()
        {
            this.ProjectTable = new HashSet<ProjectTable>();
        }
    
        public int Id { get; set; }
        public string FileRepoName { get; set; }
        public int FilesId { get; set; }
    
        public virtual ICollection<ProjectTable> ProjectTable { get; set; }
    }
}
