//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VM.DataAccessLayer.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodDrinkProjectAssignment
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int FoodDrinkId { get; set; }
        public double FoodDrinkPrice { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public bool IsEnabled { get; set; }
        public double HowMany { get; set; }
        public string Description { get; set; }
    
        public virtual FoodDrinkTable FoodDrinkTable { get; set; }
        public virtual ProjectTable ProjectTable { get; set; }
    }
}
