//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VM.DataAccessLayer.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodDrinkTable
    {
        public FoodDrinkTable()
        {
            this.FoodDrinkProjectAssignment = new HashSet<FoodDrinkProjectAssignment>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string ShortNameProduct { get; set; }
        public int MeasureId { get; set; }
        public string Description { get; set; }
        public string PhotoPath { get; set; }
        public int ProviderId { get; set; }
        public Nullable<double> HowMuch { get; set; }
    
        public virtual ICollection<FoodDrinkProjectAssignment> FoodDrinkProjectAssignment { get; set; }
        public virtual MeasureTable MeasureTable { get; set; }
        public virtual ProviderFoodCoastTable ProviderFoodCoastTable { get; set; }
    }
}
