//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VM.DataAccessLayer.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUserAssociateTable
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> RemovedTime { get; set; }
        public bool Locked { get; set; }
        public bool IsOwner { get; set; }
    
        public virtual AccountTable AccountTable { get; set; }
        public virtual ProjectTable ProjectTable { get; set; }
    }
}
