//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VM.DataAccessLayer.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTable
    {
        public ProjectTable()
        {
            this.FoodDrinkProjectAssignment = new HashSet<FoodDrinkProjectAssignment>();
            this.PaymentTable = new HashSet<PaymentTable>();
            this.ModuleProjectAssociation = new HashSet<ModuleProjectAssociation>();
            this.ProjectUserAssociateTable = new HashSet<ProjectUserAssociateTable>();
        }
    
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Removed { get; set; }
        public bool IsVisible { get; set; }
        public Nullable<int> FileRepositoryId { get; set; }
        public Nullable<int> AvailableModulesId { get; set; }
    
        public virtual FileRepositoryTable FileRepositoryTable { get; set; }
        public virtual ICollection<FoodDrinkProjectAssignment> FoodDrinkProjectAssignment { get; set; }
        public virtual ICollection<PaymentTable> PaymentTable { get; set; }
        public virtual ICollection<ModuleProjectAssociation> ModuleProjectAssociation { get; set; }
        public virtual ICollection<ProjectUserAssociateTable> ProjectUserAssociateTable { get; set; }
    }
}
