//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VM.DataAccessLayer.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderFoodCoastTable
    {
        public ProviderFoodCoastTable()
        {
            this.FoodDrinkTable = new HashSet<FoodDrinkTable>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string ProviderName { get; set; }
        public string ProviderSurname { get; set; }
        public string City { get; set; }
        public string CityCode { get; set; }
        public string Street { get; set; }
        public Nullable<int> No { get; set; }
        public string BankAccountNo { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<FoodDrinkTable> FoodDrinkTable { get; set; }
    }
}
