//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VM.DataAccessLayer.EDM
{
    using VM.DataAccessLayer.Defaults;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    
    public partial class VirtualManagerDatabaseContainer : DbContext
    {
        public VirtualManagerDatabaseContainer()
            : base(ConnectionString.Main)
        {
        }
    	
        public virtual DbSet<AccountClaimsTable> AccountClaimsTable { get; set; }
        public virtual DbSet<AccountLoginTable> AccountLoginTable { get; set; }
        public virtual DbSet<AccountRoleTable> AccountRoleTable { get; set; }
        public virtual DbSet<AccountTable> AccountTable { get; set; }
        public virtual DbSet<AccountUserRoleTable> AccountUserRoleTable { get; set; }
        public virtual DbSet<AlmostAccountTable> AlmostAccountTable { get; set; }
        public virtual DbSet<FileRepositoryTable> FileRepositoryTable { get; set; }
        public virtual DbSet<FileTable> FileTable { get; set; }
        public virtual DbSet<FoodDrinkProjectAssignment> FoodDrinkProjectAssignment { get; set; }
        public virtual DbSet<FoodDrinkTable> FoodDrinkTable { get; set; }
        public virtual DbSet<Key> Key { get; set; }
        public virtual DbSet<MeasureTable> MeasureTable { get; set; }
        public virtual DbSet<PaymentTable> PaymentTable { get; set; }
        public virtual DbSet<ProviderFoodCoastTable> ProviderFoodCoastTable { get; set; }
        public virtual DbSet<TemporaryTable> TemporaryTable { get; set; }
        public virtual DbSet<WorkAgreementTable> WorkAgreementTable { get; set; }
        public virtual DbSet<ModuleProjectAssociation> ModuleProjectAssociation { get; set; }
        public virtual DbSet<ModuleTable> ModuleTable { get; set; }
        public virtual DbSet<ProjectTable> ProjectTable { get; set; }
        public virtual DbSet<ProjectUserAssociateTable> ProjectUserAssociateTable { get; set; }
        public virtual DbSet<UserAssociationTable> UserAssociationTable { get; set; }
        public virtual DbSet<UserDetails> UserDetails { get; set; }
        public virtual DbSet<DepartmentTable> DepartmentTable { get; set; }
        public virtual DbSet<WorkerGroupTable> WorkerGroupTable { get; set; }
        public virtual DbSet<CountryZoneTable> CountryZoneTable { get; set; }
    }
}
