//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VM.DataAccessLayer.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkAgreementTable
    {
        public WorkAgreementTable()
        {
            this.PaymentTable = new HashSet<PaymentTable>();
        }
    
        public int Id { get; set; }
        public string AgreeementType { get; set; }
        public Nullable<int> Cost { get; set; }
        public string PerTime { get; set; }
        public Nullable<System.DateTime> AgreementTimeFrom { get; set; }
        public Nullable<System.DateTime> AgreementTimeTo { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<PaymentTable> PaymentTable { get; set; }
    }
}
